// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyulapnrniifktabiltp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5dWxhcG5ybmlpZmt0YWJpbHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTA2MzMsImV4cCI6MjA3MTY4NjYzM30.bjcNdKcutWXWnD-f_FZ3vzGyfbHcobfPcWyJePeeX-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});